id: de.bbmri.fhir
canonical: https://fhir.bbmri.de
version: 1.3.0-preview
name: BBMRI_DE_IG
title: BBMRI.de/GBA Implementation Guide
status: active
publisher:
    name: bbmri.de
    url: bbmri.de
    email: feedback@germanbiobanknode.de
description: Profiles for the BBMRI.de / GBA biobanking project.
license: CC-BY-SA-4.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.uv.ips: 0.3.0
  de.basisprofil.r4:
    uri: https://simplifier.net/packages/de.basisprofil.r4/0.9.6/files/129540
    version: 0.9.6
parameters:
  show-inherited-invariants: false
  path-binary: input/other
copyrightYear: 2020+
releaseLabel: CI Build
path-binary: input/other


menu:
  IG Home: index.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Profile Overview: 1_overview.html
  How to Join the Sample Locator: 2_howtoJoin.html
  Background:
    Mappings: 3_mappings.html
    Referenced IGs: 4_referencedIGs.html
    Build ETL with TOS: 6_etlTalent.html
    Quality Measures: 7_qualityMeasures.html
  Support:
    Instructions: 5_support.html
    Downloads: 8_downloads.html
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
