name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install Jekyll
      run: sudo gem install jekyll

    - name: Install Sushi
      run: sudo npm install -g fsh-sushi@1.0.2

    - name: Check out Git repository
      uses: actions/checkout@v2.3.4

    - name: Run Sushi
      run: sushi .

    - name: Create Input Cache
      run: mkdir input-cache

    - name: Download Publisher
      run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/download/1.1.25/publisher.jar -O input-cache/publisher.jar

    - name: List Dirs
      run: ls -lR

    - name: Run Publisher
      run: java -jar input-cache/publisher.jar -ig ig.ini

    - name: Download Validator
      run: wget -q https://github.com/hapifhir/org.hl7.fhir.core/releases/download/5.3.11/validator_cli.jar -O validator.jar

    - name: Run Validator
      run: java -jar validator.jar -tx n/a -ig output/validator-de.bbmri.fhir.pack -ig de.basisprofil.r4#0.9.6 -version 4.0.1 input/examples

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: output
